set(PAIRS_FILES
        ${CMAKE_CURRENT_LIST_DIR}/VariableAbstract.h
        ${CMAKE_CURRENT_LIST_DIR}/VariableAbstract.cpp
        ${CMAKE_CURRENT_LIST_DIR}/Pair.h
        ${CMAKE_CURRENT_LIST_DIR}/Pair.cpp
        ${CMAKE_CURRENT_LIST_DIR}/Stock.h
        ${CMAKE_CURRENT_LIST_DIR}/Stock.cpp
        ${CMAKE_CURRENT_LIST_DIR}/Crypto.h
        ${CMAKE_CURRENT_LIST_DIR}/Crypto.cpp
        ${CMAKE_CURRENT_LIST_DIR}/Currency.h
        ${CMAKE_CURRENT_LIST_DIR}/Currency.cpp
        ${CMAKE_CURRENT_LIST_DIR}/Tick.h
        ${CMAKE_CURRENT_LIST_DIR}/Tick.cpp
        ${CMAKE_CURRENT_LIST_DIR}/ExceptionVariableDb.h
        ${CMAKE_CURRENT_LIST_DIR}/ExceptionVariableDb.cpp
        ${CMAKE_CURRENT_LIST_DIR}/TickDelegate.h
        ${CMAKE_CURRENT_LIST_DIR}/TickDelegate.cpp
)

